spring.application.name=server

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

firebase.config.base64=${FIREBASE_CONFIG_BASE64}

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

backblaze.b2.access-key=${BACKBLAZE_B2_ACCESS_KEY}
backblaze.b2.secret-key=${BACKBLAZE_B2_SECRET_KEY}
backblaze.b2.bucket-name=${BACKBLAZE_B2_BUCKET_NAME}
backblaze.b2.region=${BACKBLAZE_B2_REGION}
backblaze.b2.public-url=${BACKBLAZE_B2_PUBLIC_URL}