ktor:
    application:
        modules:
            - com.anshtya.jetx.server.ApplicationKt.module
    deployment:
        port: 8080
db:
  name: $?DB_NAME
  host: $?DB_HOST
  user: $?DB_USER
  password: $?DB_PASSWORD